# Usa una imagen base de MySQL
FROM mysql:latest

# Define variables de entorno para la base de datos
ENV MYSQL_ROOT_PASSWORD=afvajdlm
ENV MYSQL_DATABASE=myafvajdlm
ENV MYSQL_USER=myuserafvajdlm
ENV MYSQL_PASSWORD=afvajdlm

# Expone el puerto 3306 para MySQL
EXPOSE 3306
